apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "manifest.fullname" . }}-env
    labels:
        {{- include "manifest.labels" . | nindent 4 }}
data:
    CONJUR_API_URL: {{ .Values.conjurApiUrl | quote  | default "https://conjur-oss"}}
    COOKIE_HTTP_SECURE: {{ .Values.httpSecureCookie | quote | default "false" }}
    PORT: {{ .Values.service.port | quote | default "8080" }}
    NODE_EXTRA_CA_CERTS: /etc/ssl/certs/conjur-certificate.pem
    CSRF_VALUE: {{ .Values.csrf | quote | default "false" }}